name: AI QA Coverage Bot

on:
  pull_request:
    paths:
    #  - '**/*.spec.js'
    #  - '**/coverage-summary.json'
         - '**'

jobs:
  ai-coverage-audit:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Run AI QA analysis
        run: |
          chmod +x scripts/*.sh
          ./scripts/github-coverage-bot.sh coverage/coverage-summary.json

      - name: Analyze failed test logs (if any)
        if: failure()
        run: |
          ./scripts/debug-test-logs.sh logs/test-failures.txt || true

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Post GPT report as PR comment
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          echo "Commenting on $PR_URL"
          gh pr comment "$PR_URL" --body-file .gpt-comment.md || echo "Comment failed"
      - name: Send GPT summary to Slack
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          chmod +x scripts/post-to-slack.sh
          ./scripts/post-to-slack.sh || echo 'Slack notification failed'