name: QA Toolkit

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.tsx'
      - 'coverage/coverage-summary.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test-unit:
    runs-on: ubuntu-latest
    outputs:
      jest_result: ${{ steps.jest.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests and generate coverage
        id: jest
        run: npm run test:unit -- --coverage > jest-output.txt
        continue-on-error: true

      - name: Upload Jest test report
        uses: actions/upload-artifact@v4
        with:
          name: jest-report
          path: jest-output.txt

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: coverage/coverage-summary.json

  test-cypress:
    runs-on: ubuntu-latest
    outputs:
      e2e_result: ${{ steps.e2e.outcome }}
      comp_result: ${{ steps.comp.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress E2E tests
        id: e2e
        run: npx cypress run --e2e > e2e-output.txt
        continue-on-error: true

      - name: Run Cypress Component tests
        id: comp
        run: npx cypress run --component > component-output.txt
        continue-on-error: true

      - name: Upload Cypress test reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-output
          path: |
            e2e-output.txt
            component-output.txt

  post-results:
    needs: [test-unit, test-cypress]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Download all test outputs
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Post combined test results to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const stripAnsi = str => str.replace(/\u001b\[[0-9;]*m/g, '');

            const jestOutput = stripAnsi(fs.readFileSync('artifacts/jest-report/jest-output.txt', 'utf8'));
            const e2eOutput = stripAnsi(fs.readFileSync('artifacts/cypress-output/e2e-output.txt', 'utf8'));
            const compOutput = stripAnsi(fs.readFileSync('artifacts/cypress-output/component-output.txt', 'utf8'));

            const jestPassed = '${{ needs.test-unit.outputs.jest_result }}' === 'success';
            const e2ePassed = '${{ needs.test-cypress.outputs.e2e_result }}' === 'success';
            const compPassed = '${{ needs.test-cypress.outputs.comp_result }}' === 'success';

            const body = [
              '## ✅ CI Test Summary',
              '',
              `**Jest Tests:** ${jestPassed ? '✅ Passed' : '❌ Issues Found'}`,
              '```txt',
              jestOutput.slice(-1500),
              '```',
              '',
              `**Cypress E2E:** ${e2ePassed ? '✅ Passed' : '❌ Issues Found'}`,
              '```txt',
              e2eOutput.slice(-1500),
              '```',
              '',
              `**Cypress Component:** ${compPassed ? '✅ Passed' : '❌ Issues Found'}`,
              '```txt',
              compOutput.slice(-1500),
              '```'
            ].join('\n');

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

  ai-coverage-audit:
    needs: test-unit
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-summary
          path: coverage/

      - name: Run AI coverage analysis
        run: |
          chmod +x scripts/*.sh
          ./scripts/github-coverage-bot.sh coverage/coverage-summary.json

      - name: Post GPT report as PR comment
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -f body="$(cat .gpt-comment.md)" \
            repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments

  notify-slack:
    needs: [post-results, ai-coverage-audit, test-unit, test-cypress]
    if: always()
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      JEST_RESULT: ${{ needs.test-unit.outputs.jest_result }}
      E2E_RESULT: ${{ needs.test-cypress.outputs.e2e_result }}
      COMP_RESULT: ${{ needs.test-cypress.outputs.comp_result }}
    steps:
      - name: Send Slack notification with rich formatting
        run: |
          start_time=$(date -u -d "${{ github.event.pull_request.updated_at }}" +%s)
          end_time=$(date -u +%s)
          total_duration_sec=$(( end_time - start_time ))
          total_duration="$(printf '%02d:%02d' $((total_duration_sec/60)) $((total_duration_sec%60)))"

          # Dummy durations since GitHub doesn't give timestamps per job directly (you could fetch from API if needed)
          jest_duration="~1 min"
          e2e_duration="~1–2 min"
          comp_duration="~1 min"

          # Test status badges
          jest_status=$([[ "$JEST_RESULT" == "success" ]] && echo "✅ Passed" || echo "❌ Failed")
          e2e_status=$([[ "$E2E_RESULT" == "success" ]] && echo "✅ Passed" || echo "❌ Failed")
          comp_status=$([[ "$COMP_RESULT" == "success" ]] && echo "✅ Passed" || echo "❌ Failed")

          pr_url="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          run_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          payload=$(jq -n \
          --arg pr_num "#${{ github.event.pull_request.number }}" \
          --arg pr_url "$pr_url" \
          --arg run_url "$run_url" \
          --arg jest "$jest_status" \
          --arg e2e "$e2e_status" \
          --arg comp "$comp_status" \
          --arg coverage "✅ Posted" \
          --arg total_duration "$total_duration" \
          --arg jest_duration "$jest_duration" \
          --arg e2e_duration "$e2e_duration" \
          --arg comp_duration "$comp_duration" \
          '{
            blocks: [
              {
                type: "header",
                text: { type: "plain_text", text: "🚦 QA CI Summary for PR \($pr_num)", emoji: true }
              },
              {
                type: "section",
                fields: [
                  { type: "mrkdwn", text: "*Jest Tests:* \($jest)\n⏱️ \($jest_duration)" },
                  { type: "mrkdwn", text: "*E2E Tests:* \($e2e)\n⏱️ \($e2e_duration)" },
                  { type: "mrkdwn", text: "*Component Tests:* \($comp)\n⏱️ \($comp_duration)" },
                  { type: "mrkdwn", text: "*AI Coverage:* \($coverage)\n⏱️ Total: \($total_duration)" }
                ]
              },
              {
                type: "actions",
                elements: [
                  {
                    type: "button",
                    text: { type: "plain_text", text: "🔍 View Pull Request", emoji: true },
                    url: $pr_url,
                    style: "primary"
                  },
                  {
                    type: "button",
                    text: { type: "plain_text", text: "📄 View CI Summary", emoji: true },
                    url: $run_url,
                    style: "default"
                  }
                ]
              },
              {
                type: "context",
                elements: [
                  { type: "mrkdwn", text: "Posted by *QA Toolkit Bot* via GitHub Actions" }
                ]
              }
            ]
          }')

          curl -X POST -H "Content-type: application/json" --data "$payload" "$SLACK_WEBHOOK_URL"


