name: QA Toolkit

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.tsx'
      - 'coverage/coverage-summary.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test-unit:
    runs-on: ubuntu-latest
    outputs:
      jest_result: ${{ steps.jest.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests and generate coverage
        id: jest
        run: npm run test:unit -- --coverage > jest-output.txt
        continue-on-error: true

      - name: Upload Jest test report
        uses: actions/upload-artifact@v4
        with:
          name: jest-report
          path: jest-output.txt

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: coverage/coverage-summary.json

  test-cypress:
    runs-on: ubuntu-latest
    outputs:
      e2e_result: ${{ steps.e2e.outcome }}
      comp_result: ${{ steps.comp.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress E2E tests
        id: e2e
        run: |
          npx cypress run --e2e > e2e-output.txt 
          cat e2e-output.txt
        continue-on-error: true

      - name: Run Cypress Component tests
        id: comp
        run: |
          npx cypress run --component > component-output.txt 
          cat component-output.txt
        continue-on-error: true

      - name: Upload Cypress test reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-output
          path: |
            e2e-output.txt
            component-output.txt

  post-results:
    needs: [test-unit, test-cypress]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Download all test outputs
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Post combined test results to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const stripAnsi = str => str.replace(/\u001b\[[0-9;]*m/g, '');

            const jestOutput = stripAnsi(fs.readFileSync('artifacts/jest-report/jest-output.txt', 'utf8'));
            const e2eOutput = stripAnsi(fs.readFileSync('artifacts/cypress-output/e2e-output.txt', 'utf8'));
            const compOutput = stripAnsi(fs.readFileSync('artifacts/cypress-output/component-output.txt', 'utf8'));

            const jestPassed = '${{ needs.test-unit.outputs.jest_result }}' === 'success';
            const e2ePassed = '${{ needs.test-cypress.outputs.e2e_result }}' === 'success';
            const compPassed = '${{ needs.test-cypress.outputs.comp_result }}' === 'success';

            const body = [
              '## ✅ CI Test Summary',
              '',
              `**Jest Tests:** ${jestPassed ? '✅ Passed' : '❌ Issues Found'}`,
              '```txt',
              jestOutput.slice(-1500),
              '```',
              '',
              `**Cypress E2E:** ${e2ePassed ? '✅ Passed' : '❌ Issues Found'}`,
              '```txt',
              e2eOutput.slice(-1500),
              '```',
              '',
              `**Cypress Component:** ${compPassed ? '✅ Passed' : '❌ Issues Found'}`,
              '```txt',
              compOutput.slice(-1500),
              '```'
            ].join('\n');

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

  # Removed AI coverage audit job due to sensitive API key
  # Removed Slack notification job due to sensitive webhook URL

